### ISSUE TITLE
Option to not configure certain notifications

### ISSUE THREAD

**Issue by AtomToast** [doums/bato#2]
First of all I really like the program, seems like a quite simple solution to the problem.

However I only care about notifications for battery low and critical events. Though when I leave out the segments for full, charging or discharging bato just spits out a error like this

```
bato error: while deserializing the config file, missing field `full` at line 1 column 10
```

Just leaving the section empty doesn't work either

**Comment by doums** [comment]
For the moment bato does not allow to pick only certain event(s). And as you can read in the [configuration](https://github.com/doums/bato/blob/master/bato.yaml) all events are required. So the errors you get are normal.

But it can be a good additional feature. When I have the time I will write it.

**Comment by doums** [comment]
I added the feature in the new release -> https://github.com/doums/bato/releases/tag/v0.1.2

Just omit putting the notification(s) you don't want in the config file.
