### ISSUE TITLE
Customize status file names

### ISSUE THREAD

**Issue by heitzmann** [doums/bato#4]
First, thanks for the program! I've been looking for a while for a small battery notification program like this.

However, on my system, the file names for the battery status are `charge_full`, `charge_full_design`, `charge_now`, and `status`, so I get an error when trying to use bato.

Maybe these names should be configurable (or the full path for each one — in which case you might even remove the `full_design` option, since the user would configure which file to use directly).

**Comment by doums** [comment]
Hi,

Effectively I discover these file names can vary. I thought they couldn't. Are you on Arch Linux as well, do you have a custom kernel or are you using the default one ?

As you suggested I will make these names configurable soon.

**Comment by heitzmann** [comment]
I'm on Arch with the custom kernel. My guess is that the naming convention might be brand dependent...

**Comment by doums** [comment]
Okay after digging a little in the Linux kernel [doc](https://www.kernel.org/doc/html/latest/power/power_supply_class.html#attributes-properties-detailed) it seems that the "Power supply class" can report its attributes in two ways `CHARGE_*` or `ENERGY_*`. I presume this is why you have `charge_*` on your machine and I have `energy_*` on mine.
I will add the logic to handle this properly, no need to add additional options to the configuration.

**Comment by heitzmann** [comment]
Sounds great!

**Comment by doums** [comment]
Release incoming :)

**Comment by doums** [comment]
Okay, this should be fixed in the new release -> https://github.com/doums/bato/releases/tag/v0.1.2
If you still get an error please open a new issue.

**Comment by JuanVqz** [comment]
Just to confirm the change works. Thank you!
Where is a good place to put the bato file?

![image](https://user-images.githubusercontent.com/7331511/96374250-28c7fa80-1137-11eb-8d0f-f4ffa856b920.png)

**Comment by doums** [comment]
Are you talking about the binary ?

**Comment by JuanVqz** [comment]
I'm talking about your changes in v0.1.2 now support charge_* 
I'm confirming it is supporting charge_*

**Comment by doums** [comment]
You said:
> Where is a good place to put the bato file?

**Comment by JuanVqz** [comment]
Yes I’m talking about the binary!

**Comment by doums** [comment]
In any folder present in your `$PATH`, typically in `/usr/bin` or `~/.local/bin`.
Run it as a _daemon_, maybe from a simple script:
```
#!/usr/bin/bash

mapfile -t pids <<< "$(pgrep -x bato)"
if [ "${#pids[@]}" -gt 0 ]; then
  for pid in "${pids[@]}"; do
    if [ -n "$pid" ]; then
      kill "$pid"
    fi
  done
fi
bato &
```
Start the script from your WM.

**Comment by JuanVqz** [comment]
@doums thank you for the script, I'm using i3wm and I put into my `~/.config/i3/config` to call it. 😀

```bash
exec_always --no-startup-id ~/.dotfiles/scripts/looking_bato.sh
```
is that the best way to use it?
