### ISSUE TITLE
Power supply file not found

### ISSUE THREAD

**Issue by wlmchen** [doums/bato#5]
When running bato, I get the error

`bato error: error while reading the file "/sys/class/power_supply/BAT0/energy_full_design": No such file or directory (os error 2)`

**Comment by wlmchen** [comment]
This occurs even after I set the `full_design` value to false

**Comment by doums** [comment]
Hi ! Are you sure the name of your battery is `BAT0` under `"/sys/class/power_supply/` please ?
- If yes, can you confirm `energy_full_design` file does not exist in this path ?
- if not you have to set the right name in your `bato.yaml` configuration file eg. `bat_name: BAT1`

**Comment by JuanVqz** [comment]
Hi @doums, I think this is related to #4, thank you for **bato** it seems so good

update: Oh! I saw this is related with the optional notification. :+1:

**Comment by doums** [comment]
You are welcome :)

open a new issue if you still get an error.

**Comment by wlmchen** [comment]
![image](https://user-images.githubusercontent.com/65417452/96374514-18f4ea00-1128-11eb-9cb8-278806f8a880.png)
I found that name is different from the default config file, but after updating the defaults seem to work. FYI lts kernel.
