### ISSUE TITLE
Notification priority settings

### ISSUE THREAD

**Issue by Kommynct** [doums/bato#7]
You should be able to set the urgency/priority of the notifications by the type of notifications, this would make it so that charging notifications can dismiss quickly, for example.

**Comment by doums** [comment]
https://github.com/doums/bato/blob/32f98297c95b1577cd5b5001204f99c7b1097243/bato.yaml#L73

**Comment by Kommynct** [comment]
I am so sorry, totally missed that I'm dumb. Control f'd for priority.
